create or replace table api_player_stats (
	player_id int,	
	team_id int,
	league varchar(5),
	season_id int,
	stat_type varchar(50),
	player varchar(255),
	team varchar(3),
	team_name varchar(255),
	games_played int,
	minutes decimal(10,2),
	points decimal(10,2),
	assists decimal(10,2),
	rebounds decimal(10,2),
	steals decimal(10,2),
	blocks decimal(10,2),
	fgm decimal(10,2),
	fga decimal(10,2),
	fgp varchar(10),
	fg3m decimal(10,2),
	fg3a decimal(10,2),
	fg3p varchar(10),
	ftm decimal(10,2),
	fta decimal(10,2),
	ftp varchar(10),
	primary key (player_id, season_id, stat_type),
	foreign key (player_id) references player (player_id),
	foreign key (team_id) references team (team_id),
	foreign key (season_id) references season (season_id)
);