create or replace table career_totals (
	player_id int,
	team_id int,
	lg varchar(4),
	season_type varchar(50),
	player varchar(255),
	team varchar(3),
	team_name varchar(255),
	active tinyint(4),
	games_played int,
	points int,
	assists int,
	rebounds int,
	steals int,
	blocks int,
	fgm int,
	fga int,
	fg3m int,
	fg3a int,
	ftm int,
	fta int,
	primary key (player_id, season_type),
	foreign key (player_id) references player (player_id),
	foreign key (team_id) references team (team_id)
);