create or replace table season_avgs (
	player_id int,
	team_id int,
	lg varchar(4),
	season_id int(11),
	season varchar(255),
	player varchar(255),
	team varchar(3),
	team_name varchar(255),
	active tinyint(4),
	points varchar(20),
	assists varchar(20),
	rebounds varchar(20),
	steals varchar(20),
	blocks varchar(20),
	fgm varchar(20),
	fga varchar(20),
	fgp varchar(10),
	fg3m varchar(20),
	fg3a varchar(20),
	fg3p varchar(10),
	ftm varchar(20),
	fta varchar(20),
	ftp varchar(10),
	primary key (player_id, team_id, season_id),
	foreign key (player_id) references player (player_id),
	foreign key (team_id) references team (team_id),
	foreign key (season_id) references season (season_id)
);