create table season_totals (
	player_id int,
	player varchar(255),
	lg varchar(4),
	season_id int(11),
	season varchar(255),
	team_id int,
	team varchar(3),
	team_name varchar(255),
	active tinyint(4),
	points int,
	assists int,
	rebounds int,
	steals int,
	blocks int,
	fgm int,
	fga int,
	fg3m int,
	fg3a int,
	ftm int,
	fta int,
	primary key (player_id, team_id, season_id),
	foreign key (player_id) references player (player_id),
	foreign key (team_id) references team (team_id),
	foreign key (season_id) references season (season_id)
);