create or replace table top_scorers (
	player_id int,	
	team_id int,
	league varchar(5),
	season_id int,
	game_id int,
	game_date date,
	player varchar(255),
	team varchar(3),
	team_name varchar(255),
	minutes int,
	points int,
	assists int,
	rebounds int,
	steals int,
	blocks int,
	fgm int,
	fga int,
	fgp varchar(10),
	fg3m int,
	fg3a int,
	fg3p varchar(10),
	ftm int,
	fta int,
	ftp varchar(10),
	primary key (player_id, game_id, team_id),
	foreign key (player_id) references player (player_id),
	foreign key (team_id) references team (team_id),
	foreign key (game_id) references game (game_id)
);
